name: vivace

repository: https://github.com/dnunez24/vivace

packages:
  - packages/**

command:
  version:
    branch: main
    includeCommitId: true
    linkToCommits: true
    message: |
      chore: release new package version

      {new_package_versions}

scripts:
  add:
    exec: dart pub add
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply .
  test:
    exec: dart test .
