name: vivace_core
description: A library for writing music applications.
version: 0.1.0
homepage: https://github.com/upperhandmusic/vivace
repository: https://github.com/upperhandmusic/vivace.git
issue_tracker: https://github.com/upperhandmusic/vivace/issues

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
