name: vivace_tools
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/upperhandmusic/vivace
repository: https://github.com/upperhandmusic/vivace.git
issue_tracker: https://github.com/upperhandmusic/vivace/issues

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  clock: ^1.1.1
  vivace_core: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
